#! /bin/bash
for i in intro definitions epi1; do
##    vredenburg hostpop1 parahostcomm rq virul-evol host_resist_tol para_resist sexsel host_manip emerg within
    for j in html docx pdf; do
    	make docs/notes/$i.$j
    done
    make docs/notes/honesty.html
done
