#! /bin/bash
for i in intro definitions epi1 vredenburg hostpop1 parahostcomm within rq virul-evol host_resist_tol para_resist coalescent host_manip sexsel emerg; do
##    sexsel host_manip emerg
    for j in html docx pdf; do
    	make docs/notes/$i.$j
    done
    if [ -f notes/$i.qmd ]; then
      make notes/${i}_final.html
      mv notes/${i}_final.html docs/notes/${i}.html
    fi
    make docs/notes/honesty.html
done
