---
title: "Assignments"
bibliography: "../eeid.bib"
---

*Last updated*: `r Sys.time()`

## Discussion questions (Part of 15% participation mark)

The idea of discussion questions is just to get you focused on reading the papers before class, and to help structure the in-class discussion. Ideally you should come up with one question that's general or conceptual and one that's more technical (what does Figure 1 mean? how did they do xxx?). Unless otherwise specified, every Friday class will be a discussion. Discussion questions are due at **6 PM** on the day before a class discussion (i.e. Friday afternoon at 6 PM for a Monday discussion), **posted to the relevant place**; late answers are definitely better than nothing. Discussion questions will be marked on a 0-10 scale.

## Mini-essays (15%)

A "mini-essay" is a 2-3 page paper (500-750 words; please double-space and use a 10-12 point font) that tries to develop an *original* idea, somehow related to the topic of the course and (perhaps) to the topics being covered in class at the moment. I *don't* want an essay reporting on a paper you read in class or in the library, although if you want to develop a new idea based on something you read that's OK. (Try not to spend more than a paragraph
of your essay introducing outside material, leaving most of the essay to develop your own ideas.)

The goal is to give you practice thinking and writing in an informal, (hopefully) low-pressure setting.

I would like the essays to express your ideas clearly and to be written well, but don't stress out about the writing: think of it more as an
opportunity to practice. Creativity is important, but so is rigorous and logical argument (for later essays, I may add more structure -- for example, "come up with an idea and then discuss how you might test it with an experiment or an observation").

Also see the sections on [Writing](https://bbolker.github.io/bio4ae3/notes/intro.html#writing), [Referencing](https://bbolker.github.io/bio4ae3/notes/intro.html#referencing), and [Citations](https://bbolker.github.io/bio4ae3/notes/intro.html#citation) in the intro notes from the first day of class.

I'd also encourage you to read @Perry1963 for fun and insight.

Some mini-essay topics invented by past students:

- could children be considered as parasites on their parents?
- how is the population of benign symbionts controlled by other symbionts and by the immune system? does understanding these mechanisms help us understand what happens when a formerly benign symbiont causes disease?
- how do hosts adapt to minimize the impact of parasites?
- how do host behavioral changes to disease that decrease host fitness - through increased predation, failure to reproduce, etc. - change host-parasite coevolutionary dynamics?
- is the specificity of primate parasites in the tropics governed mostly by population size, or more by differences in digestive morphology and physiology?

- [example mini-essays from past students](https://mcmasteru365.sharepoint.com/:f:/r/sites/Section_2221-1863/Class%20Materials/mini-essay%20examples?csf=1&web=1&e=Sldxl0)

## Term paper (25%)

The term paper can be on any  topic of your choice having to do with the ecology or evolution of infectious disease or parasites. 
You can focus on a particular parasite, or a particular host-parasite system, or a general phenomenon that's illustrated by several different host-parasite systems ...
It should be 10-15 pages long and give a clear, well-written synthesis and discussion of past and current research on the topic. It should cover concepts as well as facts/natural history; for example, how does some particular host-parasite example illustrate some of the concepts discussed in class? This is a chance for you to go into some depth. Ideally, your paper will also include at least some discussion of the open questions or future directions in the field.

I expect most of the references to be articles in the peer-reviewed literature; some books and a few web URLs are acceptable. Everything
should be properly cited in the style of your choice.

- a paragraph or two laying out your topic, and giving three references, is due on February 8 (1 month into the term), at the end of the day.
- your first draft is due on March 16, one month later. **This should be a finished paper representing your best effort**: the better the
 draft, the better feedback you will get from your peers/the TA/me.
- you will have one week to critique one of your peers' papers (using peerScholar)
- the final draft of the paper will be due at the end of the term.

### Past term paper topics

- evolution of virulence, with a focus on *Wohlbachia*
- *Ehrlichiosis* (an emerging tick-borne disease of mammals); effects of climate change and challenges of vaccine development
- evolution of antibiotic resistance; history, mechanism, and study in lab settings
- host switching in malaria
- population genetics of host resistance evolution
- evolution and management of antibiotic-resistance tuberculosis
- evolution and management of H5N1 avian influenza
- host switches in HIV
- evolution and management of MRSA (methicillin-resistant *Staphylococcus aureus*)

(most of these are evolutionary topics but there's no reason not to pick a more ecological topic ...)

## Emerging disease presentation (10%)

Work in a group to write a paper describing a *fictional* (but realistic) emerging disease. It could have a human, non-human animal, or plant origin. Give basic natural history and biological details such as:

- taxonomic classification (virus, bacteria, fungus, metazoan parasite? What other organisms is it related to?)
- host(s): What is its host range? Does its life cycle comprise multiple hosts?
- epidemiology: what is its R0, doubling time, generation time (if applicable)?
- host impact: what are the symptoms, fitness impacts, case fatality rate?
- host interactions: how do the encounter and compatibility filters work? Can hosts be resistant or tolerant? Can the pathogen evade resistance? What determines virulence?

Flesh out the details: why is the disease spreading now? Does it have biological characteristics that make it particularly interesting? Are there significant behavioral, ecosystem, economic, cultural impacts? With your group, write up a 4-5 page (double-spaced) description.

## Midterm 1 (25%)

The midterm test will consist of definitions, short-answer questions, and essay questions. You will be given a large set of essay questions beforehand, some of which will be asked on the midterm.

You should know a variety of examples so that you can use them in your short answers and essays.

- [midterm from a previous (2009) iteration of this course](./eeid2009-midterm.pdf)
- [essay topics](./midterm-topics.html)

## Midterm 2 (10%)

This is a low-stakes test to encourage you to pay attention to ideas that are presented after the midterm test (there is no final exam). It will (probably) consist of definitions, short-answers, and maybe an essay.

- [essay topics](./final-topics.html)

## References
